jwt:
    secret: springBootIsNice!

spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://postgresql:3306/dating-app?serverTimezone=UTC&characterEncoding=utf8
#    username: db_user
#    password: password

#  liquibase:
#    change-log: db/changelog/db.changelog.xml


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dating-app
    username: dbuser
    password: dbpassword
  #    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5433}/${POSTGRES_DATABASE:dating-app}?user=${POSTGRES_USER:dbuser}&password=${POSTGRES_PASSWORD:dbpassword}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

cors-policies: http://localhost:4200, http://127.0.0.1:4200
registration-verify-url: http://localhost:4200

logging:
  level:
    root: info
    com.example: debug
    org.springframework.web: info
    org.springframework.security.web: info
    org.hibernate: error

cloud.cloud_name: dwhzipyci
cloud.api_key: 761315847795885
cloud.api_secret: YGDsjH8TQegI8J_AXNxaQJRLlgM




