jwt:
    secret: springBootIsNice!

spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://postgresql:3306/dating-app?serverTimezone=UTC&characterEncoding=utf8
#    username: db_user
#    password: password

#  liquibase:
#    change-log: db/changelog/db.changelog.xml


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-ch1fgcqut4m00rpm4dt0-a.oregon-postgres.render.com:5432/database_dating_app
    username: database_dating_app_user
    password: PnNE1BIdjNswoVc99l1urorDZAxDANZw
  #    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5433}/${POSTGRES_DATABASE:dating-app}?user=${POSTGRES_USER:dbuser}&password=${POSTGRES_PASSWORD:dbpassword}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

cors-policies: http://localhost:4200, http://127.0.0.1:4200
registration-verify-url: http://localhost:4200

logging:
  level:
    root: info
    com.example: debug
    org.springframework.web: info
    org.springframework.security.web: info
    org.hibernate: error

cloud.cloud_name: dwhzipyci
cloud.api_key: 761315847795885
cloud.api_secret: YGDsjH8TQegI8J_AXNxaQJRLlgM




